name: Cloud-Concierge Drift Detection
on:
  workflow_dispatch:
    branches:
      - master

jobs:
 drift-detection:
    runs-on: ubuntu-latest
    steps:

    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_1 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_1 }}
        aws-region: us-east-1
      run: |
        echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV

    

    - name: Pull cloud-concierge Docker image
      run: docker pull dragondropcloud/cloud-concierge:latest

   # Step 3: Run the cloud-concierge Docker container.
    - name: Run Cloud Concierge container
      run: |
        docker run --env-file ./my-env-file.env \
          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -v ${{ github.workspace }}/main:/main \
          -w /main \
          dragondropcloud/cloud-concierge:latest


    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.CLOUD_CONCIERGE_TOKEN }}
        commit-message: Update cloud state
        branch: cloud-concierge-results
        title: Cloud Concierge Results
        body: This PR contains the latest cloud state and codified resources.