name: Cloud-Concierge Drift Detection
on:
  workflow_dispatch:
    branches:
      - master

jobs:
 drift-detection:
    runs-on: ubuntu-latest
    steps:

    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_1 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_1 }}
        aws-region: us-east-1

    - name: Pull cloud-concierge Docker image
      run: docker pull dragondropcloud/cloud-concierge:latest

   # Step 3: Run the cloud-concierge Docker container.
    - name: Run cloud-concierge container
      run: |
        docker run --env-file ./my-aws-env.env \
        -e AWS_ACCESS_KEY_1=$(aws configure get aws_access_key_id) \
        -e AWS_SECRET_ACCESS_KEY_1=$(aws configure get aws_secret_access_key) \
        -v main:/main \
        -w /main \
        dragondropcloud/cloud-concierge:latest


    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.CLOUD_CONCIERGE_TOKEN }}
        commit-message: Update cloud state
        branch: cloud-concierge-results
        title: Cloud Concierge Results
        body: This PR contains the latest cloud state and codified resources.