name: Cloud-Concierge Drift Detection
on:
  workflow_dispatch:
    branches:
      - master

jobs:
 drift-detection:
    runs-on: ubuntu-latest
    steps:

    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_1 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_1 }}
        aws-region: us-east-1

    - name: Pull cloud-concierge Docker image
      run: docker pull dragondropcloud/cloud-concierge:latest

   # Step 3: Run the cloud-concierge Docker container.
    - name: Run cloud-concierge container
      run: |
        docker run -v main:/main -v ~/.aws:/main/credentials/aws:ro -w /main dragondropcloud/cloud-concierge:latest

   # Step 6: Output Drift Detection Results
    - name: Display Drift Detection Results
      run: |
        cat drift_detection_results.txt